name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]

defaults:
  run:
    shell: bash

jobs:
    steps:
      - uses: actions/checkout@v4

      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup target add wasm32-unknown-unknown

      - name: Build contract
        run: cargo build

      - name: Run tests
        run: cargo test
